resortId: soyujima-229
schemaVersion: "2026-06-28"
name:
  ja: 創遊村229スキーランド
  en: Soyujima 229 Ski Land
japowResortId: 100
strategy:
  ja: 田子牛とニンニクの美食を満喫した後、極上のナイター非圧雪パウダーを独占する大人のローカルステイ。
  en: Monopolize uncrowded powder snow at night after savoring premium Takko beef and garlic in Japan's garlic capital.
copyFrom: sichinohe-lp
