import fs from "node:fs";
import path from "node:path";
import { ROOT } from "./japow-lookup.mjs";
import {
  loadBatch,
  getNextPending,
  getByRank,
  getById,
} from "./batch-io.mjs";

export function slugify(nameJa) {
  return nameJa
    ? nameJa
        .replace(/[（）()・]/g, " ")
        .replace(/\s+/g, "-")
        .replace(/[^\w\u3040-\u30ff\u4e00-\u9faf-]/gi, "")
        .toLowerCase()
    : "unknown";
}

export function buildResortPrompt(item, batchMeta) {
  const japowHint =
    item.japowResortId != null
      ? `JAPOW ID: **${item.japowResortId}**（要再確認）`
      : item.nameJa
        ? `JAPOW ID: **要調査** — 「${item.nameJa}」で RESORTS一覧.txt を検索`
        : "JAPOW ID: **要調査**";

  const nameBlock =
    item.nameJa != null
      ? `- 施設名: **${item.nameJa}**${item.nameEn ? ` / ${item.nameEn}` : ""}`
      : `- 施設名: **バッチ #${item.rank} — Gem マスターリスト参照**`;

  return `# Deep Research 依頼 — LP Factory バッチ ${batchMeta.batchId}

## 対象
- 優先順位: **#${item.rank}** / 30
${nameBlock}
- registry id（案）: \`${item.id ?? slugify(item.nameJa ?? `rank-${item.rank}`)}\`
- ${japowHint}

## 命令
上記スキー場について **Deep Research** を実行し、\`configs/lp-batch/gem-system-prompt.md\` の「出力フォーマット」に従った **LP戦略レポート** を 1 本出力してください。

### 重点調査
1. 公式サイト・運営・リフト/コース/料金/営業時間
2. 鉄道・IC・空港・冬季道路規制
3. インバウンド向け **戦略1行** と目玉 1〜3
4. 周辺 **飲食・温泉・観光**（各 表形式、出典 URL 必須）
5. 推奨 LP archetype と複製元（sichinohe-lp / biei-lp / shinjo-lp / sapporo-kokusai-lp 等）
${item.salesAngle ? `\n### 営業コンテキスト（選定理由）\n${item.salesAngle}\n- デジタル課題: ${item.digitalGap ?? "自治体ポータル依存"}\n- 提案軸: ${item.subscriptionPitch ?? "サブスク型多言語LP"}\n- archetype ヒント: \`${item.archetypeHint ?? "要調査"}\` · 複製元ヒント: \`${item.copyFromHint ?? "shinjo-lp"}\`` : ""}

### 出力後
レポートを \`docs/research/inbox/{registry-id}.md\` に保存できるよう、**## 0. メタデータ** に registry id と japowResortId を必ず記載してください。

---
*Generated by lp-factory prompt-builder · ${new Date().toISOString()}*
`;
}

let cachedGemSystem = null;
let cachedMarketing = null;

export function loadGemSystemPrompt() {
  if (cachedGemSystem) return cachedGemSystem;
  const p = path.join(ROOT, "configs", "lp-batch", "gem-system-prompt.md");
  cachedGemSystem = fs.readFileSync(p, "utf8");
  return cachedGemSystem;
}

export function loadMarketingPrompt() {
  if (cachedMarketing) return cachedMarketing;
  const p = path.join(ROOT, "configs", "lp-batch", "gem-marketing-prompt.md");
  cachedMarketing = fs.readFileSync(p, "utf8");
  return cachedMarketing;
}

function normalizeResortName(name) {
  return String(name)
    .replace(/\s+/g, "")
    .replace(/スキー場|スキーリゾート|ゲレンデ/g, "")
    .toLowerCase();
}

/** @param {import('./batch-io.mjs').BatchFile['resorts']} resorts */
export function findByNameJa(resorts, nameJa) {
  const q = normalizeResortName(nameJa);
  if (!q) return null;
  const exact = resorts.find((r) => r.nameJa && normalizeResortName(r.nameJa) === q);
  if (exact) return exact;
  return (
    resorts.find((r) => {
      if (!r.nameJa) return false;
      const n = normalizeResortName(r.nameJa);
      return n.includes(q) || q.includes(n);
    }) ?? null
  );
}

/** Full Deep Research input: LP Factory template. */
export function buildDeepResearchInput(item, batchMeta, profile = "lp-factory") {
  if (profile === "marketing") {
    return buildMarketingResearchInput(item, batchMeta);
  }
  const system = loadGemSystemPrompt();
  const task = buildResortPrompt(item, batchMeta);
  return `${system}

---

# 今回の調査タスク

${task}

上記フォーマットどおり **Markdown レポートのみ** を出力してください（前置き・後書き不要）。`;
}

/** ゲレンデリサーチャー Gem と同等 — 施設名だけ渡す。 */
export function buildMarketingResearchInput(item, batchMeta) {
  const system = loadMarketingPrompt();
  const name = item.nameJa ?? item.id ?? "unknown";
  const hints = [];
  if (item.japowResortId != null) hints.push(`JAPOW ID（参考）: ${item.japowResortId}`);
  if (item.id) hints.push(`registry id（案）: ${item.id}`);
  if (item.copyFromHint) hints.push(`LP 複製元ヒント: ${item.copyFromHint}`);
  if (item.salesAngle) hints.push(`営業コンテキスト: ${item.salesAngle}`);

  return `${system}

---

# 今回の調査対象

**${name}**

${hints.length ? hints.map((h) => `- ${h}`).join("\n") : ""}

Deep Research を開始し、上記フォーマットどおり **Markdown レポートのみ** を出力してください。`;
}

export function parseBatchArgs(argv) {
  const opts = {
    batch: "configs/lp-batch/batch-21-30.json",
    next: false,
    rank: null,
    id: null,
    name: null,
    prompt: "marketing",
  };
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--next") opts.next = true;
    else if (a === "--rank") opts.rank = Number(argv[++i]);
    else if (a === "--id") opts.id = argv[++i];
    else if (a === "--name") opts.name = argv[++i];
    else if (a === "--batch") opts.batch = argv[++i];
    else if (a === "--prompt") opts.prompt = argv[++i];
  }
  return opts;
}

export function resolveBatchItem(data, opts) {
  if (opts.name) {
    const item = findByNameJa(data.resorts, opts.name);
    if (!item) {
      throw new Error(`「${opts.name}」は batch JSON に見つかりません。batch-21-30.json を確認するか --rank / --id を使ってください。`);
    }
    return item;
  }
  if (opts.next) {
    const item = getNextPending(data);
    if (!item) throw new Error("No pending/research items in batch.");
    return item;
  }
  if (opts.rank != null) {
    const item = getByRank(data, opts.rank);
    if (!item) throw new Error(`Rank ${opts.rank} not found.`);
    return item;
  }
  if (opts.id) {
    const item = getById(data, opts.id);
    if (!item) throw new Error(`id ${opts.id} not found in batch.`);
    return item;
  }
  throw new Error("Specify --name, --next, --rank N, or --id slug.");
}

export function loadBatchItem(opts) {
  const { abs, data } = loadBatch(opts.batch);
  const item = resolveBatchItem(data, opts);
  return { abs, data, item };
}
